package com.letterball.entity;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_staff.ID
     *
     * @mbggenerated Fri Jul 10 14:35:05 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_staff.NICK_NAME
     *
     * @mbggenerated Fri Jul 10 14:35:05 CST 2020
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_staff.MOBILE
     *
     * @mbggenerated Fri Jul 10 14:35:05 CST 2020
     */
    private String mobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.ID
     *
     * @return the value of tb_staff.ID
     *
     * @mbggenerated Fri Jul 10 14:35:05 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.ID
     *
     * @param id the value for tb_staff.ID
     *
     * @mbggenerated Fri Jul 10 14:35:05 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.NICK_NAME
     *
     * @return the value of tb_staff.NICK_NAME
     *
     * @mbggenerated Fri Jul 10 14:35:05 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.NICK_NAME
     *
     * @param nickName the value for tb_staff.NICK_NAME
     *
     * @mbggenerated Fri Jul 10 14:35:05 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.MOBILE
     *
     * @return the value of tb_staff.MOBILE
     *
     * @mbggenerated Fri Jul 10 14:35:05 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.MOBILE
     *
     * @param mobile the value for tb_staff.MOBILE
     *
     * @mbggenerated Fri Jul 10 14:35:05 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
}