package com.letterball.entity;

import java.util.Date;

public class Subject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_subject.id
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_subject.title
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_subject.parent_id
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_subject.sort
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_subject.gmt_create
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_subject.gmt_modified
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_subject.id
     *
     * @return the value of edu_subject.id
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_subject.id
     *
     * @param id the value for edu_subject.id
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_subject.title
     *
     * @return the value of edu_subject.title
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_subject.title
     *
     * @param title the value for edu_subject.title
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_subject.parent_id
     *
     * @return the value of edu_subject.parent_id
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_subject.parent_id
     *
     * @param parentId the value for edu_subject.parent_id
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_subject.sort
     *
     * @return the value of edu_subject.sort
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_subject.sort
     *
     * @param sort the value for edu_subject.sort
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_subject.gmt_create
     *
     * @return the value of edu_subject.gmt_create
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_subject.gmt_create
     *
     * @param gmtCreate the value for edu_subject.gmt_create
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_subject.gmt_modified
     *
     * @return the value of edu_subject.gmt_modified
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_subject.gmt_modified
     *
     * @param gmtModified the value for edu_subject.gmt_modified
     *
     * @mbggenerated Tue Sep 08 20:03:07 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}